[pytest]
testpaths = tests
pythonpath = .
python_files = test_*.py
python_functions = test_*
addopts = -v --tb=short
filterwarnings =
    ignore::DeprecationWarning

[coverage:run]
source = priorauth
omit =
    priorauth/worker.py
    */tests/*

[coverage:report]
show_missing = True
skip_covered = False
fail_under = 65
