from datetime import datetime, timezone
from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from priorauth.models.pipeline import PipelineResponse

DISCLAIMER = (
    "Draft generated by Prior Auth Agent for clinical review. "
    "Verify all information against the source chart before payer submission."
)


def _styles() -> dict[str, ParagraphStyle]:
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle(
            "Title",
            parent=base["Heading1"],
            fontSize=18,
            spaceAfter=6,
            textColor=colors.HexColor("#0f172a"),
        ),
        "subtitle": ParagraphStyle(
            "Subtitle",
            parent=base["Normal"],
            fontSize=10,
            textColor=colors.HexColor("#64748b"),
            spaceAfter=14,
        ),
        "heading": ParagraphStyle(
            "SectionHeading",
            parent=base["Heading2"],
            fontSize=12,
            spaceBefore=14,
            spaceAfter=8,
            textColor=colors.HexColor("#1e40af"),
        ),
        "body": ParagraphStyle(
            "Body",
            parent=base["Normal"],
            fontSize=10,
            leading=14,
            textColor=colors.HexColor("#334155"),
        ),
        "label": ParagraphStyle(
            "Label",
            parent=base["Normal"],
            fontSize=9,
            textColor=colors.HexColor("#64748b"),
        ),
        "disclaimer": ParagraphStyle(
            "Disclaimer",
            parent=base["Normal"],
            fontSize=8,
            textColor=colors.HexColor("#94a3b8"),
            spaceBefore=20,
        ),
    }


def _escape(text: str) -> str:
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )


def _field_table(rows: list[tuple[str, str]], styles: dict[str, ParagraphStyle]) -> Table:
    data = [
        [
            Paragraph(_escape(label), styles["label"]),
            Paragraph(_escape(value), styles["body"]),
        ]
        for label, value in rows
    ]
    table = Table(data, colWidths=[1.6 * inch, 4.6 * inch])
    table.setStyle(
        TableStyle(
            [
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                ("TOPPADDING", (0, 0), (-1, -1), 2),
            ]
        )
    )
    return table


def _bullet_list(items: list[str], styles: dict[str, ParagraphStyle]) -> list:
    flowables = []
    for item in items:
        flowables.append(
            Paragraph(f"• {_escape(item)}", styles["body"])
        )
    return flowables


def build_portfolio_pdf(result: PipelineResponse) -> bytes:
    """Build a payer-ready prior authorization portfolio PDF."""
    buffer = BytesIO()
    styles = _styles()
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=0.75 * inch,
        leftMargin=0.75 * inch,
        topMargin=0.75 * inch,
        bottomMargin=0.75 * inch,
    )

    story: list = [
        Paragraph("Prior Authorization Request Package", styles["title"]),
        Paragraph(f"Generated {generated_at}", styles["subtitle"]),
    ]

    pa = result.prior_auth_request
    if pa:
        story.append(Paragraph("Prior Authorization Request", styles["heading"]))
        story.append(
            _field_table(
                [
                    ("Payer", pa.payer),
                    ("Procedure", f"{pa.procedure_description} (CPT {pa.cpt_code})"),
                    ("Diagnosis", f"{pa.diagnosis_description} (ICD-10 {pa.icd10_code})"),
                ],
                styles,
            )
        )
        story.append(Spacer(1, 8))
        story.append(Paragraph("Clinical Justification", styles["label"]))
        story.append(Paragraph(_escape(pa.clinical_justification), styles["body"]))
        if pa.supporting_facts:
            story.append(Spacer(1, 8))
            story.append(Paragraph("Supporting Facts", styles["label"]))
            story.extend(_bullet_list(pa.supporting_facts, styles))
    else:
        story.append(Paragraph("Prior Authorization Request", styles["heading"]))
        story.append(
            Paragraph(
                "No prior authorization draft was generated for this case.",
                styles["body"],
            )
        )

    if result.matched_rules:
        story.append(Paragraph("Matched Payer Rules", styles["heading"]))
        rule_rows = [["Rule ID", "CPT", "Description", "Auth Required"]]
        for rule in result.matched_rules:
            rule_rows.append(
                [
                    rule.id,
                    rule.procedure_cpt,
                    rule.description[:60] + ("…" if len(rule.description) > 60 else ""),
                    "Yes" if rule.requires_prior_auth else "No",
                ]
            )
        rule_table = Table(rule_rows, colWidths=[1.1 * inch, 0.7 * inch, 2.8 * inch, 0.9 * inch])
        rule_table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f1f5f9")),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.HexColor("#475569")),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("FONTSIZE", (0, 0), (-1, -1), 9),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                    ("TOPPADDING", (0, 0), (-1, -1), 4),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ]
            )
        )
        story.append(rule_table)

    if result.criteria_validation and result.criteria_validation.rules:
        story.append(Paragraph("Criteria Validation", styles["heading"]))
        story.append(
            Paragraph(_escape(result.criteria_validation.summary), styles["body"])
        )
        for rule_result in result.criteria_validation.rules:
            story.append(Spacer(1, 6))
            story.append(
                Paragraph(
                    f"<b>{_escape(rule_result.rule_id)}</b> — "
                    f"{rule_result.required_met}/{rule_result.required_total} required met · "
                    f"Status: {_escape(rule_result.readiness)}",
                    styles["body"],
                )
            )
            for criterion in rule_result.criteria:
                status_label = criterion.status.replace("_", " ").upper()
                story.append(
                    Paragraph(
                        f"  [{status_label}] {_escape(criterion.criterion_id)}: "
                        f"{_escape(criterion.detail)}",
                        styles["body"],
                    )
                )

    story.append(Paragraph("Clinical Summary", styles["heading"]))
    ext = result.extraction
    story.append(Paragraph(_escape(ext.patient_summary), styles["body"]))
    story.append(Spacer(1, 6))

    if ext.diagnoses:
        dx_lines = [
            f"{d.description} ({d.icd10_code or 'no code'})" for d in ext.diagnoses
        ]
        story.append(Paragraph("Diagnoses", styles["label"]))
        story.extend(_bullet_list(dx_lines, styles))

    if ext.procedures:
        proc_lines = [
            f"{p.description} (CPT {p.cpt_code or 'N/A'})" for p in ext.procedures
        ]
        story.append(Spacer(1, 4))
        story.append(Paragraph("Procedures", styles["label"]))
        story.extend(_bullet_list(proc_lines, styles))

    evidence = ext.clinical_evidence
    if evidence:
        evidence_rows: list[tuple[str, str]] = []
        if evidence.conservative_therapy_weeks is not None:
            types = ", ".join(evidence.conservative_therapy_types) or "—"
            evidence_rows.append(
                ("Conservative therapy", f"{evidence.conservative_therapy_weeks} weeks ({types})")
            )
        if evidence.imaging_studies:
            imaging = "; ".join(
                f"{s.modality} {s.body_part or ''}: {s.finding or 'documented'}".strip()
                for s in evidence.imaging_studies
            )
            evidence_rows.append(("Imaging", imaging))
        if evidence.clinical_findings:
            evidence_rows.append(("Exam findings", "; ".join(evidence.clinical_findings)))
        if evidence_rows:
            story.append(Spacer(1, 6))
            story.append(Paragraph("Clinical Evidence", styles["label"]))
            story.append(_field_table(evidence_rows, styles))

    if result.evaluation:
        story.append(Paragraph("Quality Evaluation", styles["heading"]))
        eval_ = result.evaluation
        story.append(
            Paragraph(
                f"Confidence score: {int(eval_.confidence_score * 100)}% — "
                f"{_escape(eval_.summary)}",
                styles["body"],
            )
        )

    if result.policy:
        story.append(Spacer(1, 8))
        story.append(
            Paragraph(
                f"Policy: {_escape(result.policy.payer)} · "
                f"{_escape(result.policy.plan_type)} · "
                f"v{_escape(result.policy.ruleset_version)}",
                styles["label"],
            )
        )

    story.append(Paragraph(_escape(DISCLAIMER), styles["disclaimer"]))

    doc.build(story)
    return buffer.getvalue()
